# Generated by Django 4.2.9 on 2025-01-08 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=24)),
                ('bio', models.TextField(blank=True, max_length=30, null=True)),
                ('profile_id', models.IntegerField(unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='avatars/')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duit', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BroHitung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_plus', models.IntegerField(default=0)),
                ('stage_minus', models.IntegerField(default=0)),
                ('stage_divide', models.IntegerField(default=0)),
                ('stage_multiply', models.IntegerField(default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bro_hitung', to='myapi.profile')),
            ],
        ),
    ]
