# Generated by Django 4.2.9 on 2025-01-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_diamondsbundle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='duit',
            new_name='diamond',
        ),
    ]
