# Generated by Django 4.2.9 on 2025-01-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_rename_duit_profile_diamond'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=125)),
                ('games_desc', models.TextField(blank=True, default='')),
                ('favourite', models.BigIntegerField(default=0)),
                ('account_played', models.BigIntegerField(default=0)),
                ('game_pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='game_pic/')),
                ('genres', models.ManyToManyField(related_name='games', to='myapi.genre')),
            ],
        ),
    ]
