# Generated by Django 4.2.9 on 2025-01-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_genre_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='games',
            name='genres',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
