# Generated by Django 4.2.9 on 2025-01-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_remove_games_genres_delete_genre_games_genres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BroHitung',
        ),
    ]
