# Generated by Django 4.2.9 on 2025-01-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_delete_brohitung'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=125)),
                ('game_description', models.TextField(blank=True, default='')),
                ('favouriteCount', models.BigIntegerField(default=0)),
                ('account_played', models.BigIntegerField(default=0)),
                ('game_picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='game_pic/')),
                ('genres', models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Games',
        ),
    ]
