# Generated by Django 4.2.9 on 2025-01-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_gamesdesc_delete_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesdesc',
            name='account_played',
        ),
        migrations.RemoveField(
            model_name='gamesdesc',
            name='favouriteCount',
        ),
        migrations.RemoveField(
            model_name='gamesdesc',
            name='game_description',
        ),
        migrations.RemoveField(
            model_name='gamesdesc',
            name='game_name',
        ),
        migrations.RemoveField(
            model_name='gamesdesc',
            name='game_picture',
        ),
        migrations.RemoveField(
            model_name='gamesdesc',
            name='genres',
        ),
    ]
