# Generated by Django 4.2.9 on 2025-01-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_remove_gamesdesc_account_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesdesc',
            name='account_played',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesdesc',
            name='favouriteCount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesdesc',
            name='game_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gamesdesc',
            name='game_name',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AddField(
            model_name='gamesdesc',
            name='game_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='game_pic/'),
        ),
        migrations.AddField(
            model_name='gamesdesc',
            name='genres',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
