# Generated by Django 4.2.9 on 2025-01-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro_hitung', '0013_remove_brohitung_game_desc_brohitung_account_played_and_more'),
        ('bro_mancing', '0011_remove_bromancing_game_desc_and_more'),
        ('myapi', '0009_gamesdesc_account_played_gamesdesc_favouritecount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamesDesc',
        ),
    ]
