# Generated by Django 4.2.9 on 2025-01-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_gamesdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesdesc',
            name='game_version',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
