# Generated by Django 4.2.9 on 2025-01-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_gamesdesc_game_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesdesc',
            old_name='favouriteCount',
            new_name='favourite_count',
        ),
    ]
