# Generated by Django 4.2.9 on 2025-01-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_rename_favouritecount_gamesdesc_favourite_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesdesc',
            name='genres',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
