# Generated by Django 4.2.9 on 2025-01-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_alter_gamesdesc_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesdesc',
            name='game_name',
            field=models.CharField(max_length=125, unique=True),
        ),
    ]
