# Generated by Django 4.2.9 on 2025-01-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_alter_gamesdesc_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesdesc',
            name='game_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
