# Generated by Django 4.2.9 on 2025-01-29 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_gamesdesc_game_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesdesc',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
