# Generated by Django 4.2.9 on 2025-01-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_gamesdesc_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesdesc',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
