# Generated by Django 4.2.9 on 2025-01-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0019_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Played',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('game_desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.gamesdesc')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.profile')),
            ],
            options={
                'unique_together': {('profile', 'game_desc')},
            },
        ),
    ]
