# Generated by Django 4.2.9 on 2025-02-03 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0024_gamesdesc_content_type_gamesdesc_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesdesc',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='gamesdesc',
            name='object_id',
        ),
    ]
