# Generated by Django 4.2.9 on 2025-02-04 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myapi', '0026_gamesdesc_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesdesc',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_content_type', to='contenttypes.contenttype'),
        ),
    ]
