# Generated by Django 4.2.9 on 2025-01-08 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroMancing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_score_and_stage', models.CharField(default='0:0', max_length=100)),
                ('last_score_and_stage', models.CharField(default='0:0', max_length=100)),
                ('coins', models.IntegerField(default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bro_mancing', to='myapi.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BroMancingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('bro_mancing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bro_mancing_item', to='bro_mancing.bromancing')),
            ],
            options={
                'unique_together': {('bro_mancing', 'item_type')},
            },
        ),
    ]
