# Generated by Django 4.2.9 on 2025-01-24 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_gamesdesc_delete_games'),
        ('bro_mancing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bromancing',
            name='game_desc',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='game_desc_bro_mancing', to='myapi.gamesdesc'),
        ),
    ]
