# Generated by Django 4.2.9 on 2025-01-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro_mancing', '0004_alter_bromancing_game_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bromancing',
            name='game_desc',
        ),
    ]
