# Generated by Django 4.2.9 on 2025-01-24 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_gamesdesc_delete_games'),
        ('bro_mancing', '0005_remove_bromancing_game_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bromancing',
            name='game_desc',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='bro_mancing_game_desc', to='myapi.gamesdesc'),
        ),
    ]
