# Generated by Django 4.2.9 on 2025-01-24 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_gamesdesc_account_played_gamesdesc_favouritecount_and_more'),
        ('bro_mancing', '0007_alter_bromancing_game_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bromancing',
            name='game_desc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bro_mancing_games', to='myapi.gamesdesc'),
        ),
    ]
