# Generated by Django 4.2.9 on 2025-01-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_mancing', '0010_alter_bromancing_game_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bromancing',
            name='game_desc',
        ),
        migrations.AddField(
            model_name='bromancing',
            name='account_played',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bromancing',
            name='favouriteCount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bromancing',
            name='game_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bromancing',
            name='game_name',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AddField(
            model_name='bromancing',
            name='game_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='game_pic/'),
        ),
        migrations.AddField(
            model_name='bromancing',
            name='genres',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
