# Generated by Django 4.2.9 on 2025-01-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro_mancing', '0011_remove_bromancing_game_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bromancing',
            name='account_played',
        ),
        migrations.RemoveField(
            model_name='bromancing',
            name='favouriteCount',
        ),
        migrations.RemoveField(
            model_name='bromancing',
            name='game_description',
        ),
        migrations.RemoveField(
            model_name='bromancing',
            name='game_name',
        ),
        migrations.RemoveField(
            model_name='bromancing',
            name='game_picture',
        ),
        migrations.RemoveField(
            model_name='bromancing',
            name='genres',
        ),
    ]
