# Generated by Django 4.2.9 on 2025-02-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_mancing', '0013_bromancing_default_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bromancing',
            name='default_score',
            field=models.JSONField(default={'error': 'no score yet'}),
        ),
    ]
