# Generated by Django 4.2.9 on 2025-02-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_mancing', '0014_alter_bromancing_default_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bromancing',
            name='default_score',
            field=models.JSONField(default=dict),
        ),
    ]
