# Generated by Django 4.2.9 on 2025-02-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro_mancing', '0015_alter_bromancing_default_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bromancing',
            name='default_score',
        ),
    ]
