# Generated by Django 4.2.9 on 2025-02-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_mancing', '0016_remove_bromancing_default_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='bromancing',
            name='default_score',
            field=models.CharField(default='no score yet'),
        ),
    ]
