# Generated by Django 4.2.9 on 2025-02-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_mancing', '0018_alter_bromancing_default_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='bromancing',
            name='average_score',
            field=models.IntegerField(default=0),
        ),
    ]
