# Generated by Django 4.2.9 on 2025-02-05 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro_mancing', '0019_bromancing_average_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bromancing',
            old_name='average_score',
            new_name='average_top_score',
        ),
    ]
