# Generated by Django 4.2.9 on 2025-02-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro_mancing', '0020_rename_average_score_bromancing_average_top_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bromancing',
            name='default_score',
        ),
    ]
