# Generated by Django 4.2.9 on 2025-02-05 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro_mancing', '0021_remove_bromancing_default_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bromancing',
            name='average_top_score',
        ),
    ]
