# Generated by Django 4.2.9 on 2025-02-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_mancing', '0022_remove_bromancing_average_top_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='bromancing',
            name='average_top_score',
            field=models.IntegerField(default=0),
        ),
    ]
