# Generated by Django 4.2.9 on 2025-01-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapi', '0006_delete_brohitung'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroHitung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_plus', models.IntegerField(default=0)),
                ('stage_minus', models.IntegerField(default=0)),
                ('stage_divide', models.IntegerField(default=0)),
                ('stage_multiply', models.IntegerField(default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bro_hitung', to='myapi.profile')),
            ],
        ),
    ]
