# Generated by Django 4.2.9 on 2025-01-24 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_gamesdesc_delete_games'),
        ('bro_hitung', '0002_brohitung_game_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brohitung',
            name='game_desc',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='game_desc_bro_hitung', to='myapi.gamesdesc'),
        ),
    ]
