# Generated by Django 4.2.9 on 2025-01-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro_hitung', '0005_brohitung_game_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brohitung',
            name='game_desc',
        ),
    ]
