# Generated by Django 4.2.9 on 2025-01-24 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_gamesdesc_account_played_gamesdesc_favouritecount_and_more'),
        ('bro_hitung', '0010_alter_brohitung_game_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brohitung',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bro_hitung_profile', to='myapi.profile'),
        ),
    ]
