# Generated by Django 4.2.9 on 2025-01-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro_hitung', '0013_remove_brohitung_game_desc_brohitung_account_played_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brohitung',
            name='account_played',
        ),
        migrations.RemoveField(
            model_name='brohitung',
            name='favouriteCount',
        ),
        migrations.RemoveField(
            model_name='brohitung',
            name='game_description',
        ),
        migrations.RemoveField(
            model_name='brohitung',
            name='game_name',
        ),
        migrations.RemoveField(
            model_name='brohitung',
            name='game_picture',
        ),
        migrations.RemoveField(
            model_name='brohitung',
            name='genres',
        ),
    ]
