# Generated by Django 4.2.9 on 2025-02-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro_hitung', '0014_remove_brohitung_account_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brohitung',
            name='default_score',
            field=models.CharField(default='no score yet'),
        ),
    ]
