# Generated by Django 4.2.9 on 2025-02-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro_hitung', '0020_alter_brohitung_default_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brohitung',
            name='default_score',
        ),
    ]
