# Generated by Django 4.2.9 on 2025-01-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
