# Generated by Django 4.2.9 on 2025-01-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0003_delete_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaksi',
        ),
    ]
