# Generated by Django 4.2.9 on 2025-01-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='transaction_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
