# Generated by Django 4.2.9 on 2025-01-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0006_alter_transaksi_transaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='real_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
