# Generated by Django 4.2.9 on 2025-01-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0007_transaksi_real_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='real_quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
