# Generated by Django 4.2.9 on 2025-01-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_delete_brohitung'),
        ('payment_gateway', '0009_alter_transaksi_real_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='myapi.profile'),
        ),
    ]
